package GUI;

import BL.Value;
import Exceptions.NoDataFoundException;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author Matthias
 */
public class LineGraph extends javax.swing.JPanel {

    private double sidePadding = 0.2;
    private double topBotPadding = 0.15;

    private int barWidth = 50;

    private List<Value> values;
    private Color color = new Color(0, 0, 200);

    private double maxValue = 0;
    private double minValue = Double.MAX_VALUE;
    
    private long minDate = Long.MAX_VALUE;
    private long maxDate = 0;
    
    /**
     * Draws a line graph over the passed values, using the highest value of
     * each day
     * @param values all values that should be included
     */
    public LineGraph(List<Value> values) throws NoDataFoundException {
        initComponents();

        this.values = values;
        
        if(values.isEmpty()) {
            throw new NoDataFoundException();
        }
        
        Collections.sort(values);

        
        for (Value value : values) {
            maxValue = Double.max(maxValue, value.getHigh());
            minValue = Double.min(minValue, value.getHigh());
            maxDate = Long.max(maxDate, value.getDate().toEpochDay());
            minDate = Long.min(minDate, value.getDate().toEpochDay());
        }
        
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;

        int w = (int) (getWidth() * (1 - sidePadding * 2));
        int h = (int) (getHeight() * (1 - topBotPadding * 2));
        int sidePxl = (int) (getWidth() * sidePadding);
        int topPxl = (int) (getHeight() * topBotPadding);
        double yAxisStartValue = maxValue - 2 * (maxValue - minValue);
        double valuePerPxl = (maxValue - yAxisStartValue) / h;
        double stepvaluesize = Math.pow(10, String.valueOf((int) (maxValue - yAxisStartValue)).length()) / 10;
        double steppixelsize = 1.0 / (valuePerPxl / stepvaluesize);

        // y axis
        g2d.setStroke(new BasicStroke(3));
        g2d.setColor(Color.black);
        g2d.drawLine(sidePxl, topPxl + h, sidePxl, topPxl);
        double yAxisValue = yAxisStartValue;
        for (double i = topPxl + h; i >= topPxl; i -= steppixelsize) {
            g2d.drawLine(sidePxl - 5, (int) i, sidePxl + 5, (int) i);
            g2d.drawString(String.format("%.2f", yAxisValue), sidePxl - 40, (int) i);
            yAxisValue += stepvaluesize;
        }

        // x axis
        g2d.drawLine(sidePxl, topPxl + h, sidePxl + w, topPxl + h);
        
        g2d.setColor(color);
        for (int i = 1; i < values.size(); i++) {
            g2d.drawLine(calcXCoord(values.get(i-1).getDate().toEpochDay(), w, sidePxl), 
                    calcYCoord(values.get(i-1).getHigh(), h, topPxl, yAxisStartValue),
                    calcXCoord(values.get(i).getDate().toEpochDay(), w, sidePxl), 
                    calcYCoord(values.get(i).getHigh(), h, topPxl, yAxisStartValue));
        }
    }
    
    private int calcXCoord(long date, int w, int sidePxl) {
        return sidePxl + (int) (w * (date - minDate) / (maxDate - minDate));
    }
    
    private int calcYCoord(double value, int h, int topPxl, double yAxisStartValue) {
        return topPxl + h - (int) (h * (value - yAxisStartValue) / (maxValue - yAxisStartValue));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
